// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoCM-IbcpCIpdAoYLjBhaUM6THM58E92c',
    appId: '1:849692561265:web:ba723d3e0226b6722630d0',
    messagingSenderId: '849692561265',
    projectId: 'nbpay-55455',
    authDomain: 'nbpay-55455.firebaseapp.com',
    storageBucket: 'nbpay-55455.firebasestorage.app',
    measurementId: 'G-CCLRZF21EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMFXaRbx4204iMDonszNFURXVu2qh8k4',
    appId: '1:849692561265:android:ea4645f3a814b8682630d0',
    messagingSenderId: '849692561265',
    projectId: 'nbpay-55455',
    storageBucket: 'nbpay-55455.firebasestorage.app',
  );
}
